#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf VTK
rm -f log.*
rm -f *.OpenFOAM

rm -f 0/cellToRegion

rm -f constant/polyMesh/boundary
rm -f constant/cellToRegion
rm -f constant/cellLevel
rm -f constant/pointLevel
 
rm -rf constant/fluid/polyMesh
rm -rf constant/solid/polyMesh

# -----------------------------------------------------------------------------
